### ISSUE TITLE
Issue on nav item hover

### ISSUE THREAD

**Issue by stephdotnet** [purplena/application-shopping#1]
I think there is a padding issue with the nav items. See the gif in attachement

![chrome_lFhdlgQnGD](https://user-images.githubusercontent.com/7047375/201854925-ed696140-46a9-467a-bd18-f0a2de212956.gif)

**Comment by stephdotnet** [comment]
The hitbox of the nav menu item should be 100% of the height of the navbar

**Comment by purplena** [comment]
Solved with https://github.com/purplena/application-shopping/commit/37a189ff669910b6eb7c79fe828eb29e7d4f7baa
