### ISSUE TITLE
Optimize css of the buttons

### ISSUE THREAD

**Issue by stephdotnet** [purplena/application-shopping#2]
I think we'll soon have a problem with the buttons, since the css should be easily reusable with common classes (ex: .btn.small.primary, etc.).

Try to create this page and see if you can find common properties to optimize the css of the buttons : https://www.figma.com/file/Fo69zGDtNtg4MOt2EBx2c5/Shopping-prices-by-Strapi---UI-Kit-%F0%9F%A7%A9?node-id=13463%3A28098&t=59Jr3AsN2FXZRzli-0

**Comment by purplena** [comment]
The separate page is created in html/SCSS
class = “BUTTON” - universall
class = “SMALL” or “MEDIUM” or “LARGE”  - manages the size of the button
class = “PRIMARY-DEFAULT”, “TERTIARY-DEFAULT”, “SUCCESS-DEFAULT”, “DANGER-DEFAULT” will activate the respective colors and already includes the pdeudo elements (&:hover, &:active, &:disabled)
separate class was created for the loading primary button. Please use class = “PRIMARY-LOADING”

Plus this info is added to the figma respective page.
